import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import HeroUIProvider from './HeroUIProvider'
import { Toaster } from 'react-hot-toast'
import { cn } from '@heroui/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} dark text-foreground bg-background h-screen w-screen`}
      >
        <HeroUIProvider>
          <Toaster
            position="top-right"
            toastOptions={{
              className: cn(
                'bg-content1 text-foreground border border-default-100 shadow-lg rounded-md',
                'dark:bg-content1 dark:text-foreground dark:border-default-100'
              ),
              style: {
                background: '#fff',
                color: '#000',
              },
            }}
          />
          {children}
        </HeroUIProvider>
      </body>
    </html>
  )
}
